---
name: zapata
channels:
  - conda-forge
  - ncar
dependencies:
  # Version lock for zeus compatibility
  - python=3.7
  - xarray==0.15.0
  - dask=2.12.0
  - distributed==2.12.0
  # Multi language support:
  - python=3.7
  - ipython
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pandas
  - cartopy
  - geocat-comp
  - geocat-datafiles
  - geocat-viz
  - ipywidgets
  - pygrib
  - tqdm
  - sphinx
  - seaborn
  - natsort
  # dev only
  - pudb
  - yapf
