---
name: zapata
channels:
  - conda-forge
  - ncar
dependencies:
  # Multi language support:
  - python=3.6
  - ipython
  - numpy
  - scipy
  - matplotlib
  - xarray
  - pandas
  - cartopy
  - geocat-comp
  - geocat-datafiles
  - geocat-viz
